exports.json = "./data.json"
exports.titile = "title"
exports.foundtable = "table[class='tbl-fund-summary']"
// exports.itemname = "商品名"
// exports.foundbase = "th"
exports.foundbasedata = "td[class='br0'] > span"
exports.url1 = "https://www.rakuten-sec.co.jp/web/fund/detail/?ID=JP90C00080J9"
exports.url2 = "https://www.rakuten-sec.co.jp/web/fund/detail/?ID=JP90C0009VE0"
